# Generated by Django 4.1.5 on 2023-01-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
